<?php
session_start();
include 'connect.php';

// Check if user is logged in (user role, not necessarily admin)
if (!isset($_SESSION['user_id'])) {
    header('Location: index.php?error=unauthorized');
    exit;
}

$user_id = $_SESSION['user_id'];
$nama_lengkap = $_SESSION['nama_lengkap'] ?? 'User';
$role = $_SESSION['role'] ?? 'user';

// Get user's shift assignments for current and next month
$current_month_start = date('Y-m-01');
$next_month_end = date('Y-m-t', strtotime('+1 month'));

$sql_shifts = "SELECT sa.*, c.nama_cabang, c.nama_shift, c.jam_masuk, c.jam_keluar
               FROM shift_assignments sa
               JOIN cabang c ON sa.cabang_id = c.id
               WHERE sa.user_id = ? 
               AND sa.tanggal_shift BETWEEN ? AND ?
               ORDER BY sa.tanggal_shift ASC";
$stmt_shifts = $pdo->prepare($sql_shifts);
$stmt_shifts->execute([$user_id, $current_month_start, $next_month_end]);
$shifts = $stmt_shifts->fetchAll(PDO::FETCH_ASSOC);

// Group shifts by date for easier display
$shifts_by_date = [];
foreach ($shifts as $shift) {
    $date = $shift['tanggal_shift'];
    $shifts_by_date[$date] = $shift;
}

// Get statistics
$total_shifts = count($shifts);
$confirmed_shifts = array_filter($shifts, fn($s) => $s['status_konfirmasi'] === 'confirmed');
$pending_shifts = array_filter($shifts, fn($s) => $s['status_konfirmasi'] === 'pending');
$declined_shifts = array_filter($shifts, fn($s) => $s['status_konfirmasi'] === 'declined');
?>
<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jadwal Shift Saya - <?= htmlspecialchars($nama_lengkap) ?></title>
    <link rel="stylesheet" href="style_modern.css?v=<?= time() ?>">
    <link rel="stylesheet" href="style_jadwal_shift.css?v=<?= time() ?>">
    <style>
        /* Override to prevent scrollbars */
        .shift-container {
            overflow: visible !important;
        }
        
        .calendar-wrapper {
            overflow: visible !important;
            overflow-x: visible !important;
            overflow-y: visible !important;
        }
        
        .calendar-table {
            overflow: visible !important;
        }
    </style>
</head>
<body>
    <?php include 'navbar.php'; ?>
    
    <div class="shift-container">
        <div class="header">
            <h1>📅 Jadwal Shift Saya</h1>
            <p>Halo, <strong><?= htmlspecialchars($nama_lengkap) ?></strong>! Kelola dan konfirmasi jadwal shift Anda di sini.</p>
        </div>
        
        <!-- Statistics Cards -->
        <div class="stats-grid">
            <div class="stat-card">
                <h3><?= $total_shifts ?></h3>
                <p>Total Shift</p>
            </div>
            <div class="stat-card pending">
                <h3><?= count($pending_shifts) ?></h3>
                <p>Menunggu Konfirmasi</p>
            </div>
            <div class="stat-card confirmed">
                <h3><?= count($confirmed_shifts) ?></h3>
                <p>Dikonfirmasi</p>
            </div>
            <div class="stat-card declined">
                <h3><?= count($declined_shifts) ?></h3>
                <p>Ditolak</p>
            </div>
        </div>
        
        <!-- Calendar Controls -->
        <div class="calendar-controls">
            <button id="prev-month">← Bulan Sebelumnya</button>
            <h2 id="current-month-year"></h2>
            <button id="next-month">Bulan Berikutnya →</button>
        </div>
        
        <!-- Calendar -->
        <div class="calendar-wrapper">
            <?php if ($total_shifts === 0): ?>
            <div style="background: #fff3cd; padding: 20px; border-radius: 10px; text-align: center; margin-bottom: 20px;">
                <h3 style="color: #856404; margin: 0 0 10px 0;">📋 Belum Ada Jadwal Shift</h3>
                <p style="color: #856404; margin: 0;">
                    Anda belum memiliki jadwal shift untuk bulan ini. 
                    Silakan hubungi admin untuk mendapatkan jadwal shift Anda.
                </p>
            </div>
            <?php endif; ?>
            
            <table class="calendar-table">
                <thead>
                    <tr>
                        <th>Minggu</th>
                        <th>Senin</th>
                        <th>Selasa</th>
                        <th>Rabu</th>
                        <th>Kamis</th>
                        <th>Jumat</th>
                        <th>Sabtu</th>
                    </tr>
                </thead>
                <tbody id="calendar-body">
                    <!-- Generated by JavaScript -->
                </tbody>
            </table>
            
            <div class="legend">
                <div class="legend-item">
                    <div class="legend-box" style="background: #fff3cd;"></div>
                    <span>Hari Ini</span>
                </div>
                <div class="legend-item">
                    <div class="legend-box" style="background: #e3f2fd;"></div>
                    <span>Ada Shift (Pending)</span>
                </div>
                <div class="legend-item">
                    <div class="legend-box" style="background: #e8f5e9;"></div>
                    <span>Shift Dikonfirmasi</span>
                </div>
                <div class="legend-item">
                    <div class="legend-box" style="background: #ffebee;"></div>
                    <span>Shift Ditolak</span>
                </div>
            </div>
        </div>
    </div>
    
    <!-- Shift Detail Modal -->
    <div id="shift-modal" class="modal">
        <div class="modal-content">
            <div class="modal-header">
                <h2>Detail Shift</h2>
                <span class="close">&times;</span>
            </div>
            <div class="modal-body" id="modal-body">
                <!-- Content filled by JavaScript -->
            </div>
            <div class="modal-footer" id="modal-footer">
                <!-- Buttons filled by JavaScript -->
            </div>
        </div>
    </div>
    
    <!-- Confirmation Modal -->
    <div id="confirm-modal" class="modal">
        <div class="modal-content">
            <div class="modal-header">
                <h2 id="confirm-modal-title">Konfirmasi Shift</h2>
                <span class="close" onclick="closeConfirmModal()">&times;</span>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label for="catatan-konfirmasi">Catatan (Opsional):</label>
                    <textarea id="catatan-konfirmasi" rows="4" placeholder="Tambahkan catatan jika diperlukan..."></textarea>
                </div>
            </div>
            <div class="modal-footer">
                <button onclick="closeConfirmModal()" style="background: #6c757d; color: white;">Batal</button>
                <button id="confirm-action-btn" style="background: #4CAF50; color: white;">Konfirmasi</button>
            </div>
        </div>
    </div>
    
    <script>
        // Data shifts from PHP
        console.log('🔧 Initializing shiftsData...');
        const shiftsData = <?= json_encode($shifts_by_date) ?>;
        console.log('📦 shiftsData loaded:', shiftsData);
        console.log('📊 Total shifts:', Object.keys(shiftsData).length);
        
        // Check if script file will load
        console.log('📜 Loading script_jadwal_shift.js...');
    </script>
    <script src="script_jadwal_shift.js?v=<?= time() ?>"></script>
</body>
</html>
